---
title: 'RMarkdown:  In Class Assignment'
author: "Alex Orman"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
## Wise Words
> That which is despicable to you, do not do to your fellow, this is the whole Torah, and the rest is commentary

[website about this quote](https://www.jewishvirtuallibrary.org/rabbi-hillel-quotes-on-judaism-and-israel)

## My Semester
|Course Number|Course Title|Instructor Name
|:-----------------|:------------------------------|:-------------------------|
| __COMM 2309__    | _Interpersonal Communication_ | Prof. Mueller            |
| __MATH 3302__    | _Probability and Statistics_  | Prof. King               |
| __PHIL 2305__    | _Contemporary Ethical Issues_ | Prof. Wrobel-Best        |

## I recommend
Who is a famous professor from University of Houston who uses qualitative data to investigate shame and other psychological traits; probably best known for her Ted Talk on vulnerability and appearances on Oprah?

### Brene Brown

```
"When I see people stand fully in their truth, or when I see someone fall down, get back up, and say, 'Damn. That really hurt, but this is important to me and I'm going in again' --my gut reaction is, 'What a badass.'"
```

Books By Brene Brown

* The Gifts of Imperfection
* Daring Greatly
* Rising Strong
* Braving the Wilderness
* Dare to Lead
* Atlas of the Heart.

